# inferenceservice.yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: ollama-predictor
  namespace: project-ollama
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
    openshift.io/display-name: "Ollama Inference Service"
  labels:
    opendatahub.io/dashboard: "true"
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    model:
      modelFormat:
        name: any
      runtime: ollama-fastapi-runtime
      # No storageUri needed – model is pulled at runtime via ollama pull
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
