# servingruntime.yaml
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: t9-fastapi-runtime
  annotations:
    openshift.io/display-name: "T9 FastAPI ServingRuntime (s390x)"
    opendatahub.io/recommended-accelerators: '[]'   # CPU only
  labels:
    opendatahub.io/dashboard: "true"
spec:
  multiModel: false
  supportedModelFormats:
    - name: t9
      version: "1"
      autoSelect: true
  protocolVersions:
    - v2
    - v1
  containers:
    - name: kserve-container
      image: quay.io/brice_patchou/ollama-s390x:t9-kserve-runtime-1.0-s390x
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: DICTIONARY_PATH
          value: /app/dictionary.txt
      resources:
        requests:
          cpu: "100m"
          memory: 256Mi
        limits:
          cpu: "1"
          memory: 1Gi
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 20
