# servingruntime.yaml
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: ollama-fastapi-runtime
  annotations:
    openshift.io/display-name: "Ollama ServingRuntime (s390x)"
    opendatahub.io/recommended-accelerators: '[]'   # CPU only
  labels:
    opendatahub.io/dashboard: "true"
spec:
  multiModel: false
  supportedModelFormats:
    - name: any
      version: "1"
      autoSelect: true
  protocolVersions:
    - v2
    - v1
  containers:
    - name: kserve-container
      image: quay.io/brice_patchou/ollama-s390x:kserve
      imagePullPolicy: Always
      ports:
        - containerPort: 11434
          protocol: TCP
      env:
        - name: OLLAMA_HOST
          value: "0.0.0.0:11434"
        - name: OLLAMA_MODELS
          value: /home/ollama/.ollama/models
        - name: OLLAMA_KEEP_ALIVE
          value: "-1m"
      resources:
        requests:
          cpu: "100m"
          memory: 256Mi
        limits:
          cpu: "1"
          memory: 1Gi
      readinessProbe:
        httpGet:
          path: /
          port: 11434
        initialDelaySeconds: 20
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 11434
        initialDelaySeconds: 30
        periodSeconds: 20
